"""empty message

Revision ID: a3380f94bfa2
Revises: 8c888e519765
Create Date: 2022-11-11 23:39:42.935684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3380f94bfa2'
down_revision = '8c888e519765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'title')
    # ### end Alembic commands ###
