"""empty message

Revision ID: f0eb61681523
Revises: a3380f94bfa2
Create Date: 2022-11-11 23:40:40.092686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0eb61681523'
down_revision = 'a3380f94bfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'date')
    # ### end Alembic commands ###
